CREATE TABLE `user` (
	`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '일련번호',
	`name` VARCHAR(50) NOT NULL COMMENT '이름',
	`email` VARCHAR(255) NOT NULL COMMENT '이메일',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
	PRIMARY KEY (`id`)
)
COMMENT='사용자 정보'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
